#!/usr/bin/env bash
# Regenerate docs/roadmap/active-roadmap.md from live GitHub Issues.
# Runs in CI (workflow: roadmap-sync.yml). Requires gh CLI + GH_TOKEN.
#
# Output: a single self-describing markdown file grouping open issues
# by status label (status:next > status:in-progress > status:inbox >
# everything else with no status), then closed-this-week, plus a
# "by RFC" and "by priority" view. The file is committed back to the
# default branch by the workflow with [skip ci].

set -euo pipefail

REPO="${REPO:-${GITHUB_REPOSITORY:-ricardo-david-francisco/WhiteLab}}"
OUT="docs/roadmap/active-roadmap.md"
NOW_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

mkdir -p "$(dirname "$OUT")"

# --- Fetch issues (pull requests are excluded by gh issue list) -------------
issues_json="$(gh issue list \
  --repo "$REPO" \
  --state all \
  --limit 500 \
  --json number,title,state,labels,assignees,createdAt,updatedAt,closedAt,url,milestone)"

# Helper: filter by jq expression and render a bullet list, or print "_None._"
render_section() {
  local title="$1"; shift
  local jq_filter="$1"; shift
  printf '\n### %s\n\n' "$title"
  local body
  body="$(printf '%s' "$issues_json" | jq -r "$jq_filter
    | sort_by(.number)
    | map(\"* [#\" + (.number|tostring) + \"](\" + .url + \") \" + .title +
        (if (.labels|length) > 0
         then \" — \" + ((.labels | map(.name) | join(\", \")))
         else \"\" end))
    | .[]")"
  if [ -z "$body" ]; then
    printf '_None._\n'
  else
    printf '%s\n' "$body"
  fi
}

has_label() {
  # usage: has_label "name" -> jq fragment '(.labels|map(.name)|index("name"))'
  printf '(.labels|map(.name)|index("%s"))' "$1"
}

{
  cat <<EOF
# Active Roadmap (auto-generated)

> **Do not edit by hand.** This file is regenerated by
> [\`.github/workflows/roadmap-sync.yml\`](../../.github/workflows/roadmap-sync.yml)
> on every issue event, after every merge to the default branch, and
> daily at 06:15 UTC. The hand-curated narrative lives in
> [\`README.md\`](README.md). The single source of truth is GitHub
> Issues; this file is a snapshot for offline reading and for the
> NotebookLM digest.

* **Generated:** \`$NOW_UTC\`
* **Repository:** \`$REPO\`
* **Source of truth:** [GitHub Issues](https://github.com/$REPO/issues)
* **Capture flow:** open GitHub Mobile → \`+\` → \`New issue\` →
  pick the *Shower thought* template. Two taps from the shower.

## How to read this file

* **Now** = work currently in progress (\`status:in-progress\`).
* **Next** = the explicit short list (\`status:next\`).
* **Inbox** = captured but not triaged (\`status:inbox\`, or any
  open issue with no status label yet — the triage step assigns
  one).
* **Recently done** = closed in the last 14 days.
* **By type** and **By priority** are cross-cuts of the same
  open issues for skim-reading.

EOF

  printf '## Now (in progress)\n'
  render_section "Open · status:in-progress" \
    "map(select(.state == \"OPEN\" and ($(has_label "status:in-progress")) ))"

  printf '\n## Next\n'
  render_section "Open · status:next" \
    "map(select(.state == \"OPEN\" and ($(has_label "status:next")) ))"

  printf '\n## Inbox (untriaged)\n'
  render_section "Open · status:inbox or no status label" \
    "map(select(.state == \"OPEN\" and (
        ($(has_label "status:inbox")) or
        (.labels | map(.name) | map(select(startswith(\"status:\"))) | length) == 0
      )))"

  printf '\n## Recently done (closed in the last 14 days)\n'
  render_section "Closed ≤14d" \
    "map(select(.state == \"CLOSED\" and .closedAt != null and
        ((now - (.closedAt | fromdateiso8601)) < (14*24*3600)) ))"

  printf '\n## By type (open issues)\n'
  for t in shower-thought rfc bug incident chore infra; do
    render_section "label: $t" \
      "map(select(.state == \"OPEN\" and ($(has_label "$t")) ))"
  done

  printf '\n## By priority (open issues)\n'
  for p in p0 p1 p2 p3; do
    render_section "label: $p" \
      "map(select(.state == \"OPEN\" and ($(has_label "$p")) ))"
  done

  printf '\n## Recent decisions (ADRs)\n\n'
  shopt -s nullglob
  adr_files=(docs/decisions/ADR-[0-9]*.md)
  if (( ${#adr_files[@]} == 0 )); then
    printf '_No ADRs recorded yet._\n'
  else
    # Sort by ADR id (lexicographic on filename works because the id
    # is zero-padded to 4 digits).
    IFS=$'\n' sorted=($(printf '%s\n' "${adr_files[@]}" | sort -r))
    unset IFS
    for f in "${sorted[@]}"; do
      id="$(grep -E '^id:' "$f" | head -1 | sed -E 's/^id:[[:space:]]*//')"
      status="$(grep -E '^status:' "$f" | head -1 | sed -E 's/^status:[[:space:]]*//')"
      title="$(grep -E '^# ' "$f" | head -1 | sed -E 's/^#[[:space:]]+//')"
      rel_path="${f#docs/}"
      printf '* [%s](../%s) — %s _(%s)_\n' \
        "$id" "$rel_path" "$title" "$status"
    done
  fi

  printf '\n---\n\n_Generated by \`tools/roadmap/sync-roadmap.sh\`._\n'
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
